/**
 * Narrative Exporter
 *
 * Export narratives in various formats (Markdown, JSON, Plain Text)
 * for sharing, archiving, and external use.
 */

import type { Narrative, NarrativeAct, NarrativeEvent } from './story_generator';

/**
 * Export format types
 */
export enum ExportFormat {
  MARKDOWN = 'markdown',
  JSON = 'json',
  PLAIN_TEXT = 'text',
  HTML = 'html'
}

/**
 * Export options
 */
export interface ExportOptions {
  format: ExportFormat;
  includeTechnicalDetails?: boolean;
  includeCommentary?: boolean;
  includeMetadata?: boolean;
  includeThemes?: boolean;
  includeInsights?: boolean;
}

/**
 * Default export options
 */
const DEFAULT_OPTIONS: ExportOptions = {
  format: ExportFormat.MARKDOWN,
  includeTechnicalDetails: true,
  includeCommentary: true,
  includeMetadata: true,
  includeThemes: true,
  includeInsights: true
};

/**
 * NarrativeExporter class
 */
export class NarrativeExporter {
  /**
   * Export narrative to specified format
   */
  export(narrative: Narrative, options: Partial<ExportOptions> = {}): string {
    const opts = { ...DEFAULT_OPTIONS, ...options };

    switch (opts.format) {
      case ExportFormat.MARKDOWN:
        return this.toMarkdown(narrative, opts);
      case ExportFormat.JSON:
        return this.toJSON(narrative, opts);
      case ExportFormat.PLAIN_TEXT:
        return this.toPlainText(narrative, opts);
      case ExportFormat.HTML:
        return this.toHTML(narrative, opts);
      default:
        throw new Error(`Unsupported export format: ${opts.format}`);
    }
  }

  /**
   * Export to Markdown
   */
  private toMarkdown(narrative: Narrative, options: ExportOptions): string {
    const lines: string[] = [];

    // Title
    lines.push(`# ${narrative.title}`);
    lines.push('');

    // Metadata
    if (options.includeMetadata) {
      lines.push('---');
      lines.push('**Generated by**: 4-Life Narrative System');
      lines.push('**Format**: Web4 Society Simulation');
      lines.push(`**Generated**: ${new Date().toISOString()}`);
      lines.push('---');
      lines.push('');
    }

    // Summary
    lines.push('## Summary');
    lines.push('');
    lines.push(narrative.summary);
    lines.push('');

    // Themes
    if (options.includeThemes && narrative.themes.length > 0) {
      lines.push('## Themes');
      lines.push('');
      narrative.themes.forEach(theme => {
        lines.push(`- **${theme}**`);
      });
      lines.push('');
    }

    // Key Insights
    if (options.includeInsights && narrative.key_insights.length > 0) {
      lines.push('## Key Insights');
      lines.push('');
      narrative.key_insights.forEach(insight => {
        lines.push(`- ${insight}`);
      });
      lines.push('');
    }

    // Acts
    lines.push('## Narrative');
    lines.push('');

    narrative.acts.forEach((act, actIndex) => {
      lines.push(`### ${act.title}`);
      lines.push('');

      act.events.forEach((event, eventIndex) => {
        // Timestamp
        lines.push(`**[${event.timestamp}]**`);
        lines.push('');

        // Description
        lines.push(event.description);
        lines.push('');

        // Technical details
        if (options.includeTechnicalDetails && event.technical_detail) {
          lines.push(`> 📚 **Technical**: ${event.technical_detail}`);
          lines.push('');
        }

        // Significance
        lines.push(`> ⚡ **Why it matters**: ${event.significance}`);
        lines.push('');

        // Separator between events (except last)
        if (eventIndex < act.events.length - 1) {
          lines.push('---');
          lines.push('');
        }
      });

      // Commentary
      if (options.includeCommentary && act.commentary) {
        lines.push('');
        lines.push('#### Commentary');
        lines.push('');
        lines.push(act.commentary);
        lines.push('');
      }

      // Separator between acts (except last)
      if (actIndex < narrative.acts.length - 1) {
        lines.push('');
        lines.push('---');
        lines.push('');
      }
    });

    // Footer
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('*Generated by [4-Life](https://github.com/dp-web4/4-life) - Making Web4 comprehensible to humans*');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Export to JSON
   */
  private toJSON(narrative: Narrative, options: ExportOptions): string {
    // Filter based on options
    const filtered: any = {
      title: narrative.title,
      summary: narrative.summary
    };

    if (options.includeThemes) {
      filtered.themes = narrative.themes;
    }

    if (options.includeInsights) {
      filtered.key_insights = narrative.key_insights;
    }

    filtered.acts = narrative.acts.map(act => {
      const filteredAct: any = {
        title: act.title,
        events: act.events.map(event => {
          const filteredEvent: any = {
            timestamp: event.timestamp,
            description: event.description,
            significance: event.significance
          };

          if (options.includeTechnicalDetails && event.technical_detail) {
            filteredEvent.technical_detail = event.technical_detail;
          }

          return filteredEvent;
        })
      };

      if (options.includeCommentary && act.commentary) {
        filteredAct.commentary = act.commentary;
      }

      return filteredAct;
    });

    if (options.includeMetadata) {
      filtered.metadata = {
        generated_by: '4-Life Narrative System',
        format: 'Web4 Society Simulation',
        timestamp: new Date().toISOString()
      };
    }

    return JSON.stringify(filtered, null, 2);
  }

  /**
   * Export to Plain Text
   */
  private toPlainText(narrative: Narrative, options: ExportOptions): string {
    const lines: string[] = [];

    // Title
    lines.push(narrative.title);
    lines.push('='.repeat(narrative.title.length));
    lines.push('');

    // Summary
    lines.push('SUMMARY');
    lines.push('-------');
    lines.push(narrative.summary);
    lines.push('');

    // Themes
    if (options.includeThemes && narrative.themes.length > 0) {
      lines.push('THEMES');
      lines.push('------');
      narrative.themes.forEach(theme => {
        lines.push(`  • ${theme}`);
      });
      lines.push('');
    }

    // Key Insights
    if (options.includeInsights && narrative.key_insights.length > 0) {
      lines.push('KEY INSIGHTS');
      lines.push('------------');
      narrative.key_insights.forEach(insight => {
        lines.push(`  • ${insight}`);
      });
      lines.push('');
    }

    // Acts
    lines.push('NARRATIVE');
    lines.push('---------');
    lines.push('');

    narrative.acts.forEach((act, actIndex) => {
      lines.push(act.title);
      lines.push('-'.repeat(act.title.length));
      lines.push('');

      act.events.forEach(event => {
        lines.push(`[${event.timestamp}]`);
        lines.push(event.description);
        lines.push('');

        if (options.includeTechnicalDetails && event.technical_detail) {
          lines.push(`  📚 Technical: ${event.technical_detail}`);
          lines.push('');
        }

        lines.push(`  ⚡ Why it matters: ${event.significance}`);
        lines.push('');
      });

      if (options.includeCommentary && act.commentary) {
        lines.push('Commentary:');
        lines.push(act.commentary);
        lines.push('');
      }

      if (actIndex < narrative.acts.length - 1) {
        lines.push('');
      }
    });

    lines.push('');
    lines.push('---');
    lines.push('Generated by 4-Life - Making Web4 comprehensible to humans');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Export to HTML
   */
  private toHTML(narrative: Narrative, options: ExportOptions): string {
    const lines: string[] = [];

    lines.push('<!DOCTYPE html>');
    lines.push('<html lang="en">');
    lines.push('<head>');
    lines.push('  <meta charset="UTF-8">');
    lines.push('  <meta name="viewport" content="width=device-width, initial-scale=1.0">');
    lines.push(`  <title>${this.escapeHtml(narrative.title)}</title>`);
    lines.push('  <style>');
    lines.push('    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #333; }');
    lines.push('    h1 { color: #1a1a1a; border-bottom: 2px solid #007acc; padding-bottom: 0.5rem; }');
    lines.push('    h2 { color: #2a2a2a; margin-top: 2rem; }');
    lines.push('    h3 { color: #3a3a3a; margin-top: 1.5rem; }');
    lines.push('    .metadata { background: #f5f5f5; padding: 1rem; border-radius: 4px; margin: 1rem 0; }');
    lines.push('    .themes { display: flex; flex-wrap: wrap; gap: 0.5rem; margin: 1rem 0; }');
    lines.push('    .theme { background: #007acc; color: white; padding: 0.25rem 0.75rem; border-radius: 12px; font-size: 0.9rem; }');
    lines.push('    .insights { background: #fffbf0; border-left: 4px solid #ffcc00; padding: 1rem; margin: 1rem 0; }');
    lines.push('    .event { margin: 2rem 0; padding: 1rem; border-left: 3px solid #007acc; }');
    lines.push('    .timestamp { color: #007acc; font-weight: bold; }');
    lines.push('    .technical { background: #f0f0f0; padding: 0.75rem; margin: 0.5rem 0; border-radius: 4px; font-size: 0.9rem; }');
    lines.push('    .significance { background: #fffbf0; padding: 0.75rem; margin: 0.5rem 0; border-radius: 4px; font-style: italic; }');
    lines.push('    .commentary { background: #f5f5f5; padding: 1rem; margin: 1rem 0; border-radius: 4px; }');
    lines.push('    .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ccc; text-align: center; color: #666; font-size: 0.9rem; }');
    lines.push('  </style>');
    lines.push('</head>');
    lines.push('<body>');

    // Title
    lines.push(`  <h1>${this.escapeHtml(narrative.title)}</h1>`);

    // Metadata
    if (options.includeMetadata) {
      lines.push('  <div class="metadata">');
      lines.push('    <strong>Generated by:</strong> 4-Life Narrative System<br>');
      lines.push('    <strong>Format:</strong> Web4 Society Simulation<br>');
      lines.push(`    <strong>Generated:</strong> ${new Date().toLocaleString()}`);
      lines.push('  </div>');
    }

    // Summary
    lines.push('  <h2>Summary</h2>');
    lines.push(`  <p>${this.escapeHtml(narrative.summary)}</p>`);

    // Themes
    if (options.includeThemes && narrative.themes.length > 0) {
      lines.push('  <h2>Themes</h2>');
      lines.push('  <div class="themes">');
      narrative.themes.forEach(theme => {
        lines.push(`    <span class="theme">${this.escapeHtml(theme)}</span>`);
      });
      lines.push('  </div>');
    }

    // Key Insights
    if (options.includeInsights && narrative.key_insights.length > 0) {
      lines.push('  <div class="insights">');
      lines.push('    <h3>Key Insights</h3>');
      lines.push('    <ul>');
      narrative.key_insights.forEach(insight => {
        lines.push(`      <li>${this.escapeHtml(insight)}</li>`);
      });
      lines.push('    </ul>');
      lines.push('  </div>');
    }

    // Acts
    lines.push('  <h2>Narrative</h2>');

    narrative.acts.forEach(act => {
      lines.push(`  <h3>${this.escapeHtml(act.title)}</h3>`);

      act.events.forEach(event => {
        lines.push('  <div class="event">');
        lines.push(`    <div class="timestamp">[${this.escapeHtml(event.timestamp)}]</div>`);
        lines.push(`    <p>${this.escapeHtml(event.description)}</p>`);

        if (options.includeTechnicalDetails && event.technical_detail) {
          lines.push(`    <div class="technical">📚 <strong>Technical:</strong> ${this.escapeHtml(event.technical_detail)}</div>`);
        }

        lines.push(`    <div class="significance">⚡ <strong>Why it matters:</strong> ${this.escapeHtml(event.significance)}</div>`);
        lines.push('  </div>');
      });

      if (options.includeCommentary && act.commentary) {
        lines.push('  <div class="commentary">');
        lines.push('    <h4>Commentary</h4>');
        lines.push(`    <p>${this.escapeHtml(act.commentary)}</p>`);
        lines.push('  </div>');
      }
    });

    // Footer
    lines.push('  <div class="footer">');
    lines.push('    Generated by <a href="https://github.com/dp-web4/4-life">4-Life</a> - Making Web4 comprehensible to humans');
    lines.push('  </div>');

    lines.push('</body>');
    lines.push('</html>');

    return lines.join('\n');
  }

  /**
   * Escape HTML special characters
   */
  private escapeHtml(text: string): string {
    const map: { [key: string]: string } = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;'
    };
    return text.replace(/[&<>"']/g, m => map[m]);
  }

  /**
   * Generate filename from narrative
   */
  static generateFilename(narrative: Narrative, format: ExportFormat): string {
    // Clean title for filename
    const cleanTitle = narrative.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');

    const timestamp = new Date().toISOString().split('T')[0];

    const extension = {
      [ExportFormat.MARKDOWN]: 'md',
      [ExportFormat.JSON]: 'json',
      [ExportFormat.PLAIN_TEXT]: 'txt',
      [ExportFormat.HTML]: 'html'
    }[format];

    return `${cleanTitle}-${timestamp}.${extension}`;
  }

  /**
   * Download narrative (browser environment)
   */
  static download(narrative: Narrative, options: Partial<ExportOptions> = {}): void {
    const exporter = new NarrativeExporter();
    const opts = { ...DEFAULT_OPTIONS, ...options };
    const content = exporter.export(narrative, opts);
    const filename = this.generateFilename(narrative, opts.format);

    // Create blob
    const mimeTypes = {
      [ExportFormat.MARKDOWN]: 'text/markdown',
      [ExportFormat.JSON]: 'application/json',
      [ExportFormat.PLAIN_TEXT]: 'text/plain',
      [ExportFormat.HTML]: 'text/html'
    };

    const blob = new Blob([content], { type: mimeTypes[opts.format] });
    const url = URL.createObjectURL(blob);

    // Create download link
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();

    // Cleanup
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  /**
   * Copy to clipboard (browser environment)
   */
  static async copyToClipboard(narrative: Narrative, options: Partial<ExportOptions> = {}): Promise<void> {
    const exporter = new NarrativeExporter();
    const opts = { ...DEFAULT_OPTIONS, ...options };
    const content = exporter.export(narrative, opts);

    if (navigator.clipboard) {
      await navigator.clipboard.writeText(content);
    } else {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = content;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }
  }
}

/**
 * Convenience export functions
 */
export function exportToMarkdown(narrative: Narrative, options?: Partial<ExportOptions>): string {
  const exporter = new NarrativeExporter();
  return exporter.export(narrative, { ...options, format: ExportFormat.MARKDOWN });
}

export function exportToJSON(narrative: Narrative, options?: Partial<ExportOptions>): string {
  const exporter = new NarrativeExporter();
  return exporter.export(narrative, { ...options, format: ExportFormat.JSON });
}

export function exportToPlainText(narrative: Narrative, options?: Partial<ExportOptions>): string {
  const exporter = new NarrativeExporter();
  return exporter.export(narrative, { ...options, format: ExportFormat.PLAIN_TEXT });
}

export function exportToHTML(narrative: Narrative, options?: Partial<ExportOptions>): string {
  const exporter = new NarrativeExporter();
  return exporter.export(narrative, { ...options, format: ExportFormat.HTML });
}
